name = "libgnat"
description = ""
version = "0.1.0-dev"

authors = ["Simon Wright"]
maintainers = ["Simon Wright <simon@pushface.org>"]
maintainers-logins = ["simonjwright"]
licenses = "GPL-3.0-or-later WITH GCC-exception-3.1"
website = ""
tags = []
