name: main

on:
  push:
  workflow-dispatch:

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      runs-on: ${{ matrix.os }}

      steps:
        - uses: actions/checkout@v2
        - uses: alire-project/setup-alire@v4
        - run:  alr run --development
