name: main

on:
  push:
  workflow_dispatch:

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-latest]
        # * macos-13 is x86_64, macos-latest is aarch64.
        # * ubuntu and windows both fail at the linking stage; they don't
        #   recognise that my rewrites override the RTS.
        # * maybe I should use -bargs -static?
        
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: alire-project/setup-alire@v4
      - run: alr build --development -- -gnatwn
      - run: alr run
        
