name: main

on:
  push:
  workflow_dispatch:

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-latest]
        # macos-13 is x86_64, macos-latest is aarch64.
        
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: alire-project/setup-alire@v4
      - run: |
          alr build --development
          alr run
        
